require("dotenv").config();
const mongoose = require("mongoose");
const Post = require("../models/Post");

const MONGODB_CONNECTION_URL =
  process.env.DB_CONNECTION_URL || "mongodb://localhost:27017/save-my-pet";

const seedData = [
  {
    name: "Prince",
    location: "80 E 7th street, 10003",
    microchipped: "Yes",
    breed: "Ginger",
    animalType: "Cat",
    sex: "Unknown",
    additionalInfo: "Friendly orange tabby with white paws",
    img: "https://placekitten.com/400/300",
    isLost: true,
    coordinates: [40.727156, -73.986441],
  },
  {
    name: "Randy",
    location: "East Village",
    microchipped: "Unknown",
    breed: "Cairn Terrier",
    animalType: "Dog",
    sex: "Unknown",
    additionalInfo: "Small scruffy dog, last seen wearing red collar",
    img: "https://placedog.net/400/300",
    isLost: true,
    coordinates: [40.79224, -73.973553],
  },
  {
    name: "Luna",
    location: "Williamsburg",
    microchipped: "Yes",
    breed: "Husky",
    animalType: "Dog",
    sex: "Female",
    additionalInfo: "Blue-eyed husky with gray/white fur",
    img: "https://placedog.net/401/300",
    isLost: true,
    coordinates: [40.744, -73.9956],
  },
  {
    name: "Mittens",
    location: "Upper West Side",
    microchipped: "No",
    breed: "Calico",
    animalType: "Cat",
    sex: "Female",
    additionalInfo: "Tri-color cat, very shy but sweet",
    img: "https://placekitten.com/401/300",
    isLost: true,
    coordinates: [40.748817, -73.985428],
  },
  {
    name: "Rocky",
    location: "Harlem",
    microchipped: "Yes",
    breed: "Pitbull",
    animalType: "Dog",
    sex: "Male",
    additionalInfo: "Brown pitbull with white chest, very friendly",
    img: "https://placedog.net/402/300",
    isLost: true,
    coordinates: [40.7527, -73.9772],
  },
  {
    name: "Whiskers",
    location: "Astoria",
    microchipped: "Unknown",
    breed: "Siamese",
    animalType: "Cat",
    sex: "Male",
    additionalInfo: "Vocal cat with blue eyes and pointed markings",
    img: "https://placekitten.com/402/300",
    isLost: true,
    coordinates: [40.7549, -73.984],
  },
  {
    name: "Max",
    location: "Brooklyn Heights",
    microchipped: "Yes",
    breed: "Golden Retriever",
    animalType: "Dog",
    sex: "Male",
    additionalInfo: "Friendly golden with slightly wavy fur",
    img: "https://placedog.net/403/300",
    isLost: true,
    coordinates: [40.7265, -73.9815],
  },
  {
    name: "Bella",
    location: "SoHo",
    microchipped: "No",
    breed: "Persian",
    animalType: "Cat",
    sex: "Female",
    additionalInfo: "Fluffy white Persian cat",
    img: "https://placekitten.com/403/300",
    isLost: false,
    coordinates: [40.7661, -73.9547],
  },
  {
    name: "Charlie",
    location: "Chelsea",
    microchipped: "Yes",
    breed: "Beagle",
    animalType: "Dog",
    sex: "Male",
    additionalInfo: "Tri-color beagle with long ears",
    img: "https://placedog.net/404/300",
    isLost: false,
    coordinates: [40.742054, -74.004821],
  },
  // Additional entries to fill larger grids
  {
    name: "Oreo",
    location: "Financial District",
    microchipped: "No",
    breed: "Tuxedo",
    animalType: "Cat",
    sex: "Male",
    additionalInfo: "Black and white cat with perfect tuxedo markings",
    img: "https://placekitten.com/404/300",
    isLost: true,
    coordinates: [40.776676, -73.971321],
  },
  {
    name: "Daisy",
    location: "Greenpoint",
    microchipped: "Yes",
    breed: "Dachshund",
    animalType: "Dog",
    sex: "Female",
    additionalInfo: "Miniature dapple dachshund",
    img: "https://placedog.net/405/300",
    isLost: false,
    coordinates: [40.776676, -73.971321],
  },
  {
    name: "Shadow",
    location: "Long Island City",
    microchipped: "Unknown",
    breed: "Black Lab",
    animalType: "Dog",
    sex: "Male",
    additionalInfo: "All black lab with yellow collar",
    img: "https://placedog.net/406/300",
    isLost: false,
    coordinates: [40.776676, -73.971321],
  },
  {
    name: "Milo",
    location: "Park Slope",
    microchipped: "Yes",
    breed: "Tabby",
    animalType: "Cat",
    sex: "Male",
    additionalInfo: "Brown tabby with M-shaped forehead marking",
    img: "https://placekitten.com/405/300",
    isLost: false,
    coordinates: [40.776676, -73.971321],
  },
  {
    name: "Lucy",
    location: "DUMBO",
    microchipped: "No",
    breed: "Poodle",
    animalType: "Dog",
    sex: "Female",
    additionalInfo: "White miniature poodle, recently groomed",
    img: "https://placedog.net/407/300",
    isLost: true,
    coordinates: [40.776676, -73.971321],
  },
  {
    name: "Simba",
    location: "Upper East Side",
    microchipped: "Yes",
    breed: "Maine Coon",
    animalType: "Cat",
    sex: "Male",
    additionalInfo: "Large orange Maine Coon with tufted ears",
    img: "https://placekitten.com/406/300",
    isLost: true,
    coordinates: [40.776676, -73.971321],
  },
  {
    name: "Bailey",
    location: "West Village",
    microchipped: "Yes",
    breed: "Cocker Spaniel",
    animalType: "Dog",
    sex: "Female",
    additionalInfo: "Golden cocker spaniel with floppy ears",
    img: "https://placedog.net/408/300",
    isLost: false,
    coordinates: [40.776676, -73.971321],
  },
  {
    name: "Loki",
    location: "Bushwick",
    microchipped: "No",
    breed: "Bengal",
    animalType: "Cat",
    sex: "Male",
    additionalInfo: "Spotted Bengal cat, very active",
    img: "https://placekitten.com/407/300",
    isLost: false,
    coordinates: [40.776676, -73.971321],
  },
  {
    name: "Zoe",
    location: "Tribeca",
    microchipped: "Yes",
    breed: "Shih Tzu",
    animalType: "Dog",
    sex: "Female",
    additionalInfo: "Small Shih Tzu with underbite",
    img: "https://placedog.net/409/300",
    isLost: false,
    coordinates: [40.776676, -73.971321],
  },
];

mongoose
  .connect(MONGODB_CONNECTION_URL)
  .then(async () => {
    console.log("Connected to MongoDB, seeding...");
    await Post.deleteMany({});
    await Post.insertMany(seedData);
    console.log("Seeding completed!");
    process.exit();
  })
  .catch((err) => {
    console.error("Seeding failed:", err);
    process.exit(1);
  });
