require("dotenv").config();
const mongoose = require("mongoose");
const Post = require("../models/Post");

const MONGODB_CONNECTION_URL =
  process.env.DB_CONNECTION_URL || "mongodb://localhost:27017/save-my-pet";

const seedData = [
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Prince",
    location: "429 11th Ave, New York, NY 10001",
    microchipped: "Yes",
    breed: "Ginger",
    animalType: "Cat",
    sex: "Unknown",
    additionalInfo: "Friendly orange tabby with white paws found near the Javits Center",
    medicalHistory: "No known medical issues, up-to-date on vaccinations as of 2023",
    img: "https://images.pexels.com/photos/774731/pexels-photo-774731.jpeg",
    coordinates: [40.75778596116167, -74.00171315664157],
    status: "Rescued",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Randy",
    location: "Grand Central Station, 10017",
    microchipped: "Unknown",
    breed: "Cairn Terrier",
    animalType: "Dog",
    sex: "Unknown",
    additionalInfo: "Small scruffy dog, last seen wearing red collar wandering through Grand Central",
    medicalHistory: "Possible hip dysplasia, limps occasionally",
    img: "https://placedog.net/400/300",
    coordinates: [40.752433361405046, -73.9782172540969],
    status: "Lost",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Luna",
    location: "180 Greenwich St, New York, NY 10007",
    microchipped: "Yes",
    breed: "Husky",
    animalType: "Dog",
    sex: "Female",
    additionalInfo: "Blue-eyed husky with gray/white fur last seen near the World Trade Center",
    medicalHistory: "Allergic to chicken, requires special diet",
    img: "https://placedog.net/401/300",
    coordinates: [40.71238588181593, -74.01316480405534],
    status: "Lost",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Mittens",
    location: "1000 5th Ave, New York, NY 10028",
    microchipped: "No",
    breed: "Calico",
    animalType: "Cat",
    sex: "Female",
    additionalInfo: "Tri-color cat, very shy but sweet missing from MET Museum area",
    medicalHistory: "History of urinary tract infections",
    img: "https://images.pexels.com/photos/127028/pexels-photo-127028.jpeg",
    coordinates: [40.77992633343864, -73.9631030283719],
    status: "Lost",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Rocky",
    location: "253 W 125th St, New York, NY 10027",
    microchipped: "Yes",
    breed: "Pitbull",
    animalType: "Dog",
    sex: "Male",
    additionalInfo: "Brown pitbull with white chest, very friendly found near the Apollo in Harlem",
    medicalHistory: "Recent dental cleaning, no major health concerns",
    img: "https://placedog.net/402/300",
    coordinates: [40.81021626925731, -73.95005799845822],
    status: "Rescued",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Whiskers",
    location: "116th and Broadway, New York, NY 10027",
    microchipped: "Unknown",
    breed: "Siamese",
    animalType: "Cat",
    sex: "Male",
    additionalInfo: "Vocal cat with blue eyes and pointed markings lost at Columbia University",
    medicalHistory: "Asthma, requires occasional inhaler use",
    img: "https://images.pexels.com/photos/2194261/pexels-photo-2194261.jpeg",
    coordinates: [40.80760370138715, -73.96255187364959],
    status: "Lost",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Max",
    location: "200 Central Prk W, New York, NY 10024",
    microchipped: "Yes",
    breed: "Golden Retriever",
    animalType: "Dog",
    sex: "Male",
    additionalInfo: "Friendly golden with slightly wavy fur in need of rescue from the Natural History Museum, trapped in the Planetarium",
    medicalHistory: "Hip dysplasia, on joint supplements",
    img: "https://placedog.net/403/300",
    coordinates: [40.78157882433646, -73.9739091368122],
    status: "Endangered",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Bella",
    location: "768 5th Ave, New York, NY 10019",
    microchipped: "No",
    breed: "Persian",
    animalType: "Cat",
    sex: "Female",
    additionalInfo: "Fluffy white Persian cat found at the Plaza Hotel",
    medicalHistory: "Requires regular grooming to prevent matting",
    img: "",
    coordinates: [40.764953802831414, -73.97432252381552],
    status: "Found",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Charlie",
    location: "405 Lexington Ave, New York, NY 10174",
    microchipped: "Yes",
    breed: "Beagle",
    animalType: "Dog",
    sex: "Male",
    additionalInfo: "Tri-color beagle with long ears scaling the Chrysler Building, needs rescue",
    medicalHistory: "Food allergies, requires grain-free diet",
    img: "https://placedog.net/404/300",
    coordinates: [40.75168705114522, -73.97549741303442],
    status: "Endangered",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Oreo",
    location: "828 Broadway, New York, NY 10003",
    microchipped: "No",
    breed: "Tuxedo",
    animalType: "Cat",
    sex: "Male",
    additionalInfo: "Black and white cat with perfect tuxedo markings last seen in The Strand Bookstore",
    medicalHistory: "No known health issues",
    img: "https://images.pexels.com/photos/19607031/pexels-photo-19607031.jpeg",
    coordinates: [40.73342239713554, -73.99096678853836],
    status: "Lost",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Daisy",
    location: "500 Pearl St, New York, NY 10007",
    microchipped: "Yes",
    breed: "Dachshund",
    animalType: "Dog",
    sex: "Female",
    additionalInfo: "Miniature dapple dachshund found at the Southern District Courthouse",
    medicalHistory: "Prone to back issues, needs help with stairs",
    img: "https://placedog.net/405/300",
    coordinates: [40.71419826689667, -74.00050802599444],
    status: "Found",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Shadow",
    location: "175 5th Ave, New York, NY 10010",
    microchipped: "Unknown",
    breed: "Black Lab",
    animalType: "Dog",
    sex: "Male",
    additionalInfo: "All black lab with yellow collar found in front of the Flatiron Building",
    medicalHistory: "Recent ear infection, cleared with medication",
    img: "https://placedog.net/406/300",
    coordinates: [40.741122338715456, -73.98962450697958],
    status: "Found",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Milo",
    location: "20 W 34th St., New York, NY 10001",
    microchipped: "Yes",
    breed: "Tabby",
    animalType: "Cat",
    sex: "Male",
    additionalInfo: "Brown tabby with M-shaped forehead marking found at the Empire State Building",
    medicalHistory: "FIV positive, needs special care",
    img: "",
    coordinates: [40.748430115352164, -73.98570938340211],
    status: "Found",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Lucy",
    location: "695 Park Ave, New York, NY 10065",
    microchipped: "No",
    breed: "Poodle",
    animalType: "Dog",
    sex: "Female",
    additionalInfo: "White miniature poodle, recently groomed lost near Hunter College",
    medicalHistory: "Recent dental work, missing two teeth",
    img: "https://placedog.net/407/300",
    coordinates: [40.767843289210894, -73.96453164933192],
    status: "Lost",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Simba",
    location: "New York, NY 10001",
    microchipped: "Yes",
    breed: "Maine Coon",
    animalType: "Cat",
    sex: "Male",
    additionalInfo: "Large orange Maine Coon with tufted ears lost near MSG",
    medicalHistory: "Heart murmur, requires annual cardiology check",
    img: "https://images.pexels.com/photos/982314/pexels-photo-982314.jpeg",
    coordinates: [40.75076657184364, -73.99343228869748],
    status: "Lost",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Bailey",
    location: "Little Island, New York, NY 10014",
    microchipped: "Yes",
    breed: "Cocker Spaniel",
    animalType: "Dog",
    sex: "Female",
    additionalInfo: "Golden cocker spaniel with floppy ears",
    medicalHistory: "Ear infections, needs weekly ear cleaning",
    img: "https://placedog.net/408/300",
    coordinates: [40.74213775724721, -74.01025985229535],
    status: "Found",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Loki",
    location: "252 First Ave Loop, New York, NY 10009",
    microchipped: "No",
    breed: "Bengal",
    animalType: "Cat",
    sex: "Male",
    additionalInfo: "Spotted Bengal cat, very active found in StuyTown",
    medicalHistory: "Hyperactive, may need behavioral training",
    img: "https://images.pexels.com/photos/16747555/pexels-photo-16747555.jpeg",
    coordinates: [40.73202020487943, -73.97785547831153],
    status: "Found",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Zoe",
    location: "525 E 68th St, New York, NY 10065",
    microchipped: "Yes",
    breed: "Shih Tzu",
    animalType: "Dog",
    sex: "Female",
    additionalInfo: "Small Shih Tzu with underbite found at Presbyterian Hospital",
    medicalHistory: "Eye issues, requires daily eye drops",
    img: "https://placedog.net/409/300",
    coordinates: [40.76438465511256, -73.95422815637781],
    status: "Found",
  },
  // Additional pets with medical history
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Oliver",
    location: "1 E 161st St, Bronx, NY 10451",
    microchipped: "Yes",
    breed: "Tabby",
    animalType: "Cat",
    sex: "Male",
    additionalInfo: "Orange tabby with white belly found near Yankee Stadium",
    medicalHistory: "Diabetes, requires insulin injections twice daily",
    img: "https://images.pexels.com/photos/2071882/pexels-photo-2071882.jpeg",
    coordinates: [40.829555, -73.926166],
    status: "Found",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Sophie",
    location: "Prospect Park West, Brooklyn, NY 11215",
    microchipped: "Yes",
    breed: "French Bulldog",
    animalType: "Dog",
    sex: "Female",
    additionalInfo: "Brindle Frenchie lost near Prospect Park bandshell",
    medicalHistory: "Brachycephalic syndrome, needs temperature regulation",
    img: "https://placedog.net/410/300",
    coordinates: [40.660203, -73.968956],
    status: "Lost",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Leo",
    location: "Queens Blvd, Rego Park, NY 11374",
    microchipped: "No",
    breed: "Ragdoll",
    animalType: "Cat",
    sex: "Male",
    additionalInfo: "Fluffy blue-eyed cat found near Queens Center Mall",
    medicalHistory: "No known health issues, very docile temperament",
    img: "https://images.pexels.com/photos/1170986/pexels-photo-1170986.jpeg",
    coordinates: [40.729538, -73.862429],
    status: "Found",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Ruby",
    location: "Staten Island Ferry Terminal, NY 10301",
    microchipped: "Yes",
    breed: "Corgi",
    animalType: "Dog",
    sex: "Female",
    additionalInfo: "Red and white Pembroke Welsh Corgi missing near ferry",
    medicalHistory: "IVDD risk, needs ramps instead of stairs",
    img: "https://placedog.net/411/300",
    coordinates: [40.642987, -74.076427],
    status: "Lost",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Gizmo",
    location: "Atlantic Ave, Brooklyn, NY 11201",
    microchipped: "No",
    breed: "Chihuahua",
    animalType: "Dog",
    sex: "Male",
    additionalInfo: "Small tan Chihuahua trembling near Barclays Center",
    medicalHistory: "Patellar luxation, may need surgery",
    img: "https://placedog.net/412/300",
    coordinates: [40.683693, -73.976124],
    status: "Rescued",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Cleo",
    location: "Roosevelt Island, NY 10044",
    microchipped: "Yes",
    breed: "Sphynx",
    animalType: "Cat",
    sex: "Female",
    additionalInfo: "Hairless cat found near the tram station",
    medicalHistory: "Requires regular skin care and sunscreen",
    img: "https://images.pexels.com/photos/4587959/pexels-photo-4587959.jpeg",
    coordinates: [40.762169, -73.949772],
    status: "Found",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Duke",
    location: "Coney Island Boardwalk, Brooklyn, NY 11224",
    microchipped: "Yes",
    breed: "Great Dane",
    animalType: "Dog",
    sex: "Male",
    additionalInfo: "Harlequin Great Dane last seen near Cyclone rollercoaster",
    medicalHistory: "Gastric dilatation-volvulus risk, needs special feeding routine",
    img: "https://placedog.net/413/300",
    coordinates: [40.574926, -73.985941],
    status: "Lost",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Misty",
    location: "Flushing Meadows Park, Queens, NY 11368",
    microchipped: "No",
    breed: "Siamese",
    animalType: "Cat",
    sex: "Female",
    additionalInfo: "Seal point Siamese near Unisphere",
    medicalHistory: "Sensitive digestive system, needs special food",
    img: "https://images.pexels.com/photos/57416/cat-sweet-kitty-animals-57416.jpeg",
    coordinates: [40.739688, -73.840843],
    status: "Lost",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Rocky",
    location: "Arthur Ave, Bronx, NY 10458",
    microchipped: "Yes",
    breed: "Boxer",
    animalType: "Dog",
    sex: "Male",
    additionalInfo: "Brindle boxer missing from Little Italy area",
    medicalHistory: "Allergic to grass, needs medication in spring/summer",
    img: "https://placedog.net/414/300",
    coordinates: [40.852455, -73.887734],
    status: "Lost",
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Lola",
    location: "Williamsburg Bridge, NY 10002",
    microchipped: "Yes",
    breed: "Pug",
    animalType: "Dog",
    sex: "Female",
    additionalInfo: "Black pug with pink collar seen on pedestrian path",
    medicalHistory: "Brachycephalic, needs cooling vest in summer",
    img: "https://placedog.net/415/300",
    coordinates: [40.712773, -73.971039],
    status: "Endangered",
  },
    {
    _id: new mongoose.Types.ObjectId(),
    name: "Toby",
    location: "Times Square, NY 10036",
    microchipped: "Yes",
    breed: "Golden Retriever",
    animalType: "Dog",
    sex: "Male",
    additionalInfo: "Friendly golden retriever with service vest missing in crowded area",
    medicalHistory: "Trained service dog, needs daily anxiety medication",
    img: "https://placedog.net/416/300",
    coordinates: [40.7580, -73.9855],
    status: "Lost"
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Mochi",
    location: "Chinatown, NY 10013",
    microchipped: "No",
    breed: "Shih Tzu",
    animalType: "Dog",
    sex: "Female",
    additionalInfo: "Small cream-colored Shih Tzu last seen near Confucius Plaza",
    medicalHistory: "Chronic dry eye, needs daily lubricating drops",
    img: "https://placedog.net/417/300",
    coordinates: [40.7158, -73.9970],
    status: "Lost"
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Salem",
    location: "Washington Square Park, NY 10012",
    microchipped: "Yes",
    breed: "Black Cat",
    animalType: "Cat",
    sex: "Male",
    additionalInfo: "All black cat with yellow eyes often seen near the arch",
    medicalHistory: "FIV positive but otherwise healthy",
    img: "https://images.pexels.com/photos/127028/pexels-photo-127028.jpeg",
    coordinates: [40.7308, -73.9973],
    status: "Found"
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Rosie",
    location: "Brooklyn Bridge Park, NY 11201",
    microchipped: "Yes",
    breed: "Labradoodle",
    animalType: "Dog",
    sex: "Female",
    additionalInfo: "Apricot colored labradoodle missing from dog run area",
    medicalHistory: "Ear infection prone, needs weekly cleaning",
    img: "https://placedog.net/418/300",
    coordinates: [40.7021, -73.9968],
    status: "Lost"
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Binx",
    location: "Central Park Zoo, NY 10023",
    microchipped: "No",
    breed: "Tuxedo",
    animalType: "Cat",
    sex: "Male",
    additionalInfo: "Black and white cat that hangs around the sea lion exhibit",
    medicalHistory: "Overweight, on prescription diet food",
    img: "https://images.pexels.com/photos/774731/pexels-photo-774731.jpeg",
    coordinates: [40.7678, -73.9718],
    status: "Found"
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Cooper",
    location: "High Line, NY 10011",
    microchipped: "Yes",
    breed: "Australian Shepherd",
    animalType: "Dog",
    sex: "Male",
    additionalInfo: "Blue merle Aussie with heterochromia (one blue eye, one brown)",
    medicalHistory: "Hip dysplasia, on joint supplements",
    img: "https://placedog.net/419/300",
    coordinates: [40.7479, -74.0048],
    status: "Rescued"
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Lily",
    location: "Bryant Park, NY 10018",
    microchipped: "No",
    breed: "Ragdoll",
    animalType: "Cat",
    sex: "Female",
    additionalInfo: "Fluffy blue-eyed cat found near the winter village",
    medicalHistory: "Recently spayed, recovering well",
    img: "https://images.pexels.com/photos/1170986/pexels-photo-1170986.jpeg",
    coordinates: [40.7536, -73.9832],
    status: "Found"
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Thor",
    location: "Battery Park, NY 10004",
    microchipped: "Yes",
    breed: "Siberian Husky",
    animalType: "Dog",
    sex: "Male",
    additionalInfo: "White husky with blue eyes escaped from leash near ferry terminal",
    medicalHistory: "Allergic to poultry, requires special diet",
    img: "https://placedog.net/420/300",
    coordinates: [40.7033, -74.0170],
    status: "Lost"
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Pepper",
    location: "Union Square, NY 10003",
    microchipped: "No",
    breed: "Jack Russell Terrier",
    animalType: "Dog",
    sex: "Female",
    additionalInfo: "Small white dog with brown spots, very energetic",
    medicalHistory: "Heart murmur, needs regular checkups",
    img: "https://placedog.net/421/300",
    coordinates: [40.7359, -73.9911],
    status: "Endangered"
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Miso",
    location: "Koreatown, NY 10001",
    microchipped: "Yes",
    breed: "Scottish Fold",
    animalType: "Cat",
    sex: "Male",
    additionalInfo: "Gray folded-ear cat missing from apartment near 32nd St",
    medicalHistory: "Arthritis in joints, needs soft bedding",
    img: "https://images.pexels.com/photos/2071873/pexels-photo-2071873.jpeg",
    coordinates: [40.7475, -73.9874],
    status: "Lost"
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Oscar",
    location: "Prospect Park, NY 11215",
    microchipped: "Yes",
    breed: "Beagle",
    animalType: "Dog",
    sex: "Male",
    additionalInfo: "Tri-color beagle last seen near the boathouse, responds to whistle",
    medicalHistory: "Food allergies, requires grain-free diet",
    img: "https://placedog.net/422/300",
    coordinates: [40.6602, -73.9690],
    status: "Lost"
},
{
    _id: new mongoose.Types.ObjectId(),
    name: "Luna",
    location: "Roosevelt Island, NY 10044",
    microchipped: "No",
    breed: "Calico",
    animalType: "Cat",
    sex: "Female",
    additionalInfo: "Very vocal calico with distinctive orange patch over left eye",
    medicalHistory: "Asthma, uses inhaler twice daily",
    img: "https://images.pexels.com/photos/1543793/pexels-photo-1543793.jpeg",
    coordinates: [40.7621, -73.9499],
    status: "Found"
},
{
    _id: new mongoose.Types.ObjectId(),
    name: "Max",
    location: "Coney Island Boardwalk, NY 11224",
    microchipped: "Yes",
    breed: "Pug",
    animalType: "Dog",
    sex: "Male",
    additionalInfo: "Fawn pug wearing a red harness, escaped near Nathan's Famous",
    medicalHistory: "Breathing issues, needs climate-controlled environment",
    img: "https://placedog.net/423/300",
    coordinates: [40.5749, -73.9850],
    status: "Lost"
},
{
    _id: new mongoose.Types.ObjectId(),
    name: "Bella",
    location: "Harlem, NY 10026",
    microchipped: "No",
    breed: "Tabby",
    animalType: "Cat",
    sex: "Female",
    additionalInfo: "Striped tabby with white paws found near Apollo Theater",
    medicalHistory: "Recently treated for fleas",
    img: "https://images.pexels.com/photos/126407/pexels-photo-126407.jpeg",
    coordinates: [40.8106, -73.9465],
    status: "Found"
},
{
    _id: new mongoose.Types.ObjectId(),
    name: "Rocky",
    location: "Yankee Stadium, NY 10451",
    microchipped: "Yes",
    breed: "Boxer",
    animalType: "Dog",
    sex: "Male",
    additionalInfo: "Brindle boxer wearing Yankees bandana, scared of loud noises",
    medicalHistory: "Recent ACL surgery, limited activity required",
    img: "https://placedog.net/424/300",
    coordinates: [40.8296, -73.9262],
    status: "Lost"
},
{
    _id: new mongoose.Types.ObjectId(),
    name: "Cleo",
    location: "Metropolitan Museum of Art, NY 10028",
    microchipped: "Yes",
    breed: "Sphynx",
    animalType: "Cat",
    sex: "Female",
    additionalInfo: "Hairless cat in pink sweater last seen near Egyptian exhibit",
    medicalHistory: "Requires special skin moisturizer",
    img: "https://images.pexels.com/photos/4587959/pexels-photo-4587959.jpeg",
    coordinates: [40.7794, -73.9632],
    status: "Lost"
},
{
    _id: new mongoose.Types.ObjectId(),
    name: "Duke",
    location: "Staten Island Ferry, NY 10301",
    microchipped: "No",
    breed: "Great Dane",
    animalType: "Dog",
    sex: "Male",
    additionalInfo: "Harlequin Great Dane, very tall with blue eyes",
    medicalHistory: "Prone to bloat, needs elevated food bowl",
    img: "https://placedog.net/425/300",
    coordinates: [40.6429, -74.0767],
    status: "Found"
},
{
    _id: new mongoose.Types.ObjectId(),
    name: "Zoe",
    location: "Greenwich Village, NY 10014",
    microchipped: "Yes",
    breed: "Maltese",
    animalType: "Dog",
    sex: "Female",
    additionalInfo: "Small white dog with pink bow, missing from Washington Mews",
    medicalHistory: "Dental issues, needs soft food",
    img: "https://placedog.net/426/300",
    coordinates: [40.7336, -73.9967],
    status: "Lost"
},
{
    _id: new mongoose.Types.ObjectId(),
    name: "Simba",
    location: "Bronx Zoo, NY 10460",
    microchipped: "No",
    breed: "Orange Tabby",
    animalType: "Cat",
    sex: "Male",
    additionalInfo: "Large orange cat often seen near zoo entrance, very friendly",
    medicalHistory: "Overweight, on diet food",
    img: "https://images.pexels.com/photos/1170986/pexels-photo-1170986.jpeg",
    coordinates: [40.8506, -73.8770],
    status: "Found"
},
{
    _id: new mongoose.Types.ObjectId(),
    name: "Lola",
    location: "DUMBO, NY 11201",
    microchipped: "Yes",
    breed: "French Bulldog",
    animalType: "Dog",
    sex: "Female",
    additionalInfo: "Blue Frenchie with one floppy ear, loves attention",
    medicalHistory: "Sensitive skin, requires special shampoo",
    img: "https://placedog.net/427/300",
    coordinates: [40.7033, -73.9886],
    status: "Rescued"
},
{
    _id: new mongoose.Types.ObjectId(),
    name: "Oliver",
    location: "Chelsea Market, NY 10011",
    microchipped: "No",
    breed: "Siamese",
    animalType: "Cat",
    sex: "Male",
    additionalInfo: "Vocal seal point Siamese found near the lobster place",
    medicalHistory: "Kidney disease, on prescription diet",
    img: "https://images.pexels.com/photos/2071882/pexels-photo-2071882.jpeg",
    coordinates: [40.7424, -74.0061],
    status: "Found"
},
{
    _id: new mongoose.Types.ObjectId(),
    name: "Milo",
    location: "Williamsburg Bridge, NY 11211",
    microchipped: "Yes",
    breed: "Corgi",
    animalType: "Dog",
    sex: "Male",
    additionalInfo: "Pembroke Welsh corgi with stubby tail, escaped during walk",
    medicalHistory: "Back problems, no stairs allowed",
    img: "https://placedog.net/428/300",
    coordinates: [40.7127, -73.9686],
    status: "Lost"
},
{
    _id: new mongoose.Types.ObjectId(),
    name: "Chloe",
    location: "Rockefeller Center, NY 10111",
    microchipped: "Yes",
    breed: "Pomeranian",
    animalType: "Dog",
    sex: "Female",
    additionalInfo: "Fluffy orange Pom wearing diamond collar, missing near ice rink",
    medicalHistory: "Luxating patellas, limited jumping",
    img: "https://placedog.net/429/300",
    coordinates: [40.7587, -73.9787],
    status: "Lost"
},
{
    _id: new mongoose.Types.ObjectId(),
    name: "Leo",
    location: "Columbia University, NY 10027",
    microchipped: "No",
    breed: "Maine Coon",
    animalType: "Cat",
    sex: "Male",
    additionalInfo: "Giant brown tabby with ear tufts, campus cat for years",
    medicalHistory: "Healthy senior cat, needs joint supplements",
    img: "https://images.pexels.com/photos/991831/pexels-photo-991831.jpeg",
    coordinates: [40.8075, -73.9626],
    status: "Found"
},
{
    _id: new mongoose.Types.ObjectId(),
    name: "Sophie",
    location: "South Street Seaport, NY 10038",
    microchipped: "Yes",
    breed: "Cockapoo",
    animalType: "Dog",
    sex: "Female",
    additionalInfo: "Curly apricot cockapoo, anxious around boats",
    medicalHistory: "Ear infections, needs weekly cleaning",
    img: "https://placedog.net/430/300",
    coordinates: [40.7074, -74.0033],
    status: "Endangered"
},
{
    _id: new mongoose.Types.ObjectId(),
    name: "Kiwi",
    location: "Upper West Side, NY 10024",
    microchipped: "No",
    breed: "Budgerigar (Parakeet)",
    animalType: "Bird",
    sex: "Female",
    additionalInfo: "Bright green and yellow parakeet with a blue tail feather, escaped from open window",
    medicalHistory: "Prone to respiratory infections, needs warm environment",
    img: "https://images.pexels.com/photos/56733/pexels-photo-56733.jpeg",
    coordinates: [40.7870, -73.9754],
    status: "Lost"
},
{
    _id: new mongoose.Types.ObjectId(),
    name: "BunBun",
    location: "Park Slope, Brooklyn, NY 11215",
    microchipped: "Yes",
    breed: "Holland Lop",
    animalType: "Rabbit",
    sex: "Male",
    additionalInfo: "Fluffy brown rabbit with floppy ears, last seen in backyard garden",
    medicalHistory: "Needs hay-based diet, prone to dental issues",
    img: "https://images.pexels.com/photos/4588065/pexels-photo-4588065.jpeg",
    coordinates: [40.6681, -73.9806],
    status: "Lost"
},
{
    _id: new mongoose.Types.ObjectId(),
    name: "Peanut",
    location: "Williamsburg, Brooklyn, NY 11249",
    microchipped: "No",
    breed: "Abyssinian Guinea Pig",
    animalType: "Guinea Pig",
    sex: "Female",
    additionalInfo: "Brown and white rosette fur, very vocal when hungry",
    medicalHistory: "Vitamin C supplements required daily",
    img: "https://images.pexels.com/photos/4587991/pexels-photo-4587991.jpeg",
    coordinates: [40.7159, -73.9650],
    status: "Found"
},
{
    _id: new mongoose.Types.ObjectId(),
    name: "Einstein",
    location: "Financial District, NY 10005",
    microchipped: "Yes",
    breed: "African Grey Parrot",
    animalType: "Bird",
    sex: "Male",
    additionalInfo: "Highly intelligent, mimics phone ringtones and alarms",
    medicalHistory: "Prone to feather plucking when stressed",
    img: "https://images.pexels.com/photos/97533/pexels-photo-97533.jpeg",
    coordinates: [40.7076, -74.0113],
    status: "Lost"
},
{
    _id: new mongoose.Types.ObjectId(),
    name: "Dusty",
    location: "Bushwick, Brooklyn, NY 11237",
    microchipped: "No",
    breed: "Standard Grey Chinchilla",
    animalType: "Chinchilla",
    sex: "Male",
    additionalInfo: "Extremely soft fur, loves dust baths",
    medicalHistory: "Heat-sensitive, needs cool environment",
    img: "https://images.pexels.com/photos/674318/pexels-photo-674318.jpeg",
    coordinates: [40.6984, -73.9205],
    status: "Found"
},
{
    _id: new mongoose.Types.ObjectId(),
    name: "Shelly",
    location: "Prospect Park Lake, Brooklyn, NY 11215",
    microchipped: "No",
    breed: "Red-Eared Slider",
    animalType: "Turtle",
    sex: "Female",
    additionalInfo: "Medium-sized turtle with red markings near ears, likely released by owner",
    medicalHistory: "Shell rot history, needs UVB light",
    img: "https://images.pexels.com/photos/8473938/pexels-photo-8473938.jpeg",
    coordinates: [40.6602, -73.9690],
    status: "Found"
},
{
    _id: new mongoose.Types.ObjectId(),
    name: "Spike",
    location: "Long Island City, Queens, NY 11101",
    microchipped: "Yes",
    breed: "African Pygmy Hedgehog",
    animalType: "Hedgehog",
    sex: "Male",
    additionalInfo: "Small, nocturnal, rolls into a ball when scared",
    medicalHistory: "Prone to obesity, needs controlled diet",
    img: "https://images.pexels.com/photos/50577/hedgehog-animal-baby-cute-50577.jpeg",
    coordinates: [40.7447, -73.9485],
    status: "Lost"
},
];

mongoose.connect(MONGODB_CONNECTION_URL)
    .then(async () => {
        console.log("Connected to MongoDB, seeding...");
        await Post.deleteMany({});
        const result = await Post.insertMany(seedData);

        // Log all created IDs
        console.log("Created pets with these IDs:");
        result.forEach(pet => {
            console.log(`Name: ${pet.name}, ID: ${pet._id}`);
        });

        process.exit();
    })
    .catch((err) => {
        console.error("Seeding failed:", err);
        process.exit(1);
    });